version: "2"

networks:
  kafka-tier:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:latest
    networks:
      - kafka-tier
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /mnt/wsl/zookeeper-data:/bitnami/zookeeper
  kafka-server-1:
    container_name: kafka-server-1
    image: docker.io/bitnami/kafka:latest
    networks:
      - kafka-tier
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /mnt/wsl/kafka-server-1-data:/bitnami/kafka
    depends_on:
      - zookeeper
  kafka-server-2:
    container_name: kafka-server-2
    image: docker.io/bitnami/kafka:latest
    networks:
      - kafka-tier
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /mnt/wsl/kafka-server-2-data:/bitnami/kafka
    depends_on:
      - kafka-server-1
  kafka-client-1:
    container_name: kafka-client-1
    image: docker.io/bitnami/kafka:latest
    networks:
      - kafka-tier
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /mnt/wsl/kafka-client-1-data:/bitnami/kafka
    depends_on:
      - kafka-server-1
  kafka-client-2:
    container_name: kafka-client-2
    image: docker.io/bitnami/kafka:latest
    networks:
      - kafka-tier
    ports:
      - "9092"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /mnt/wsl/kafka-client-2-data:/bitnami/kafka
    depends_on:
      - kafka-server-2